remote_theme: pmarsceill/just-the-docs

title: Asta PC Dev Log
description: Development log

just_the_docs:
  color_scheme: dark
  favicon_ico: ""
  logo: ""
  aux_links:
    GitHub Repo:
      - https://github.com/ark-hopf/ast-pc_dev_log

# Tell Jekyll to include root CSS files
include:
  - just-the-docs-dark.css

markdown: kramdown

