remote_theme: just-the-docs/just-the-docs

title: Asta PC Dev Log
description: Development log

just_the_docs:
  color_scheme: dark
  favicon_ico: ""
  logo: ""
  aux_links:
    GitHub Repo:
      - https://github.com/ark-hopf/ast-pc_dev_log

sass:
  sass_dir: assets/css
  style: compressed

markdown: kramdown

